### ISSUE TITLE
XQuartz 2.8.5beta5 crashes during menu opening and closing in nedit (Motif based editor)

### ISSUE THREAD

**Issue by dpeterc** [XQuartz/XQuartz#317]
I was testing nedit with the latest Xquartz 2.8.5beta5 and have placed nedit window slightly on the left, so that left edge was out of the visible area.
Then I clicked the mouse and while still pressed, moved it over the line of menus (File, Edit, Search, Preferences) which opens and closes the menus based on the clicked menu button.
If the menu button is not completely visible (has negative coordinates), then popup menu opens not a the mouse position, but shifted to the right, so that it is visible. This is probably a Motif feature, and it works the same also on Linux.
While doing this, XQuartz crashed whit the following report
[xquartz2.8.5-beta5-crash.txt](https://github.com/XQuartz/XQuartz/files/10401949/xquartz2.8.5-beta5-crash.txt)
If if would help debug the problem, and you can make me debug version of XQuartz, I am willing to try it, in order to give even more detailed crash report.
Maybe it is related to issue 308, but I am not sure...
https://github.com/XQuartz/XQuartz/issues/308

**Comment by jeremyhu** [comment]
Reproduced with ASan:

```
Application Specific Information:
X.Org X Server 21.1.6
=================================================================
==82933==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00011e45076c at pc 0x0001053e8d14 bp 0x00016bcc3580 sp 0x00016bcc2d38
READ of size 756 at 0x00011e45076c thread T5
#0 0x1053e8d10 in __asan_memcpy+0x1a4 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x3cd10)
#1 0x1044d1714 in fbBlt fbblt.c:82
#2 0x1045026b0 in fbCopyWindowProc fbwindow.c:86
#3 0x10452eb68 in miCopyRegion micopy.c:121
#4 0x104481884 in RootlessResizeCopyWindow rootlessWindow.c:693
#5 0x104591b08 in miResizeWindow miwindow.c:573
#6 0x10447cd0c in RootlessResizeWindow rootlessWindow.c:1118
#7 0x10473ea40 in ConfigureWindow window.c:2411
#8 0x1045f8de4 in ProcConfigureWindow dispatch.c:984
#9 0x1045f01f0 in Dispatch dispatch.c:551
#10 0x1046410b8 in dix_main main.c:272
#11 0x104430ca0 in server_thread quartzStartup.c:65
#12 0x19050a068 in _pthread_start+0x90 (libsystem_pthread.dylib:arm64e+0x7068)
#13 0x190504e28 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e28)
0x00011e45076c is located 148 bytes to the left of 374528-byte region [0x00011e450800,0x00011e4abf00)
allocated by thread T5 here:
#0 0x1053eaf2c in wrap_realloc+0x9c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x3ef2c)
#1 0x104be26f4 in xreallocarray reallocarray.c:42
#2 0x10447b4b4 in StartFrameResize rootlessWindow.c:923
#3 0x10447cb64 in RootlessResizeWindow rootlessWindow.c:1111
#4 0x10473ea40 in ConfigureWindow window.c:2411
#5 0x1045f8de4 in ProcConfigureWindow dispatch.c:984
#6 0x1045f01f0 in Dispatch dispatch.c:551
#7 0x1046410b8 in dix_main main.c:272
#8 0x104430ca0 in server_thread quartzStartup.c:65
#9 0x19050a068 in _pthread_start+0x90 (libsystem_pthread.dylib:arm64e+0x7068)
#10 0x190504e28 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x1e28)
Thread T5 created by T0 here:
#0 0x1053e4c5c in wrap_pthread_create+0x54 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x38c5c)
#1 0x1044309a8 in create_thread quartzStartup.c:80
#2 0x1044305a0 in QuartzInitServer quartzStartup.c:97
#3 0x10440acc0 in X11ApplicationMain X11Application.m:801
#4 0x104416ab4 in X11ControllerMain X11Controller.m:922
#5 0x104431098 in server_main quartzStartup.c:138
#6 0x1043fee18 in do_start_x11_server bundle-main.c:400
#7 0x1043f9dc8 in _Xstart_x11_server mach_startupServer.c:192
#8 0x1043fafcc in mach_startup_server mach_startupServer.c:402
#9 0x1904d2084 in mach_msg_server+0x1a0 (libsystem_kernel.dylib:arm64e+0x9084)
#10 0x1043ff5a8 in main bundle-main.c:725
#11 0x1901dfe4c  (<unknown module>)
SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x3cd10) in __asan_memcpy+0x1a4
Shadow bytes around the buggy address:
0x007023caa090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x007023caa0a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x007023caa0b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x007023caa0c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x007023caa0d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x007023caa0e0: fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa
0x007023caa0f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
0x007023caa100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x007023caa110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x007023caa120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0x007023caa130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
Addressable:           00
Partially addressable: 01 02 03 04 05 06 07
Heap left redzone:       fa
Freed heap region:       fd
Stack left redzone:      f1
Stack mid redzone:       f2
Stack right redzone:     f3
Stack after return:      f5
Stack use after scope:   f8
Global redzone:          f9
Global init order:       f6
Poisoned by user:        f7
Container overflow:      fc
Array cookie:            ac
Intra object redzone:    bb
ASan internal:           fe
Left alloca redzone:     ca
Right alloca redzone:    cb
==82933==ABORTING
```

I've also updated the build script to use ASan for executables in beta builds, so that will help as well.

**Comment by jeremyhu** [comment]
Fixed in my patch series.  This should be addressed in the next beta, which I'll try to get out this weekend.

**Comment by jeremyhu** [comment]
Please give beta6 a whirl.

**Comment by dpeterc** [comment]
I have tried with beta6 and could no longer reproduce this bug, so consider it fixed.
Thanks for the quick action, and I am sure the ASan will help in further debugging, if necessary.
